= Serialization

image:https://img.shields.io/badge/vert.x-4.1.2-purple.svg[link="https://vertx.io"]
image:https://github.com/cyface-de/serialization/actions/workflows/gradle_build.yml/badge.svg[link="https://github.com/cyface-de/serialization/actions/workflows/gradle_build.yml"]
image:https://github.com/cyface-de/serialization/actions/workflows/gradle_publish.yml/badge.svg[link="https://github.com/cyface-de/serialization/actions/workflows/gradle_publish.yml"]

This application represents the https://cyface.de[Cyface] serialization software.

It is used to de-/serialize the Cyface Binary Format which contains traffic data from Cyface measurement devices, such as our sensor box or our smartphone application.

Our smartphone SDK is available as GPL application for https://github.com/cyface-de/android-backend[Android] and https://github.com/cyface-de/ios-backend[iOS] (or as https://github.com/cyface-de/ios-podspecs[Podspec]) as well.

If you require this software under a closed source license for you own projects, please https://www.cyface.de/#kontakt[contact us].

Changes between versions are found in the link:https://github.com/cyface-de/serialization/releases[Release Section].

The project uses link:https://gradle.org/[Gradle] as the build system.
It is set up as a Gradle multi project build.
There are two general categories of sub-projects.
One are executable programs fulfilling a certain task of the Cyface backend.
Others are libraries shared by several Cyface executables.
The executables are grouped in the sub-project `executables` while the libraries are grouped in `libs`.
The following sections provide an overview about those projects.

== Overview

.link:#_libraries[Libraries]
* link:#_model[Model]
* link:#_serializer[Serializer]

.General information
* link:#_release_a_new_version[Release a new Version]
* link:#_publishing_artifacts_to_github_packages_manually[Publishing Artifacts to GitHub Packages manually]
* link:#_licensing[Licensing]


== Libraries

[#_model]
=== Model

Model classes shared between multiple projects.

[#_serializer]
=== Serializer

Serialization wrappers for the Cyface Binary Format.


[#_release_a_new_version]
== Release a new Version

See https://github.com/cyface-de/data-collector#release-a-new-version[Cyface Collector Readme]

* `cyfaceAndroidBackendVersion` in root `build.gradle` is automatically set by the CI
* Just tag the release and push the tag to Github
* The Github package is automatically published when a new version is tagged and pushed by our
https://github.com/cyface-de/serialization/actions[Github Actions] to
the https://github.com/cyface-de/serialization/packages[Github Registry]
* The tag is automatically marked as a 'new Release' on https://github.com/cyface-de/serialization/releases[Github]


[#_publishing_artifacts_to_github_packages_manually]
== Publishing artifacts to GitHub Packages manually

The artifacts produced by this project are distributed via link:https://github.com/features/packages[GitHubPackages].
Before you can publish artifacts you need to rename `gradle.properties.template` to `gradle.properties` and enter your GitHub credentials.
How to obtain these credentials is described link:https://help.github.com/en/github/managing-packages-with-github-packages/about-github-packages#about-tokens[here].

To publish a new version of an artifact you need to:

1. Increase the version number of the sub-project within the `build.gradle` file
2. Call `./gradlew publish`

This will upload a new artifact to GitHub packages with the new version.
GitHub Packages will not accept to overwrite an existing version or to upload a lower version.
This project uses link:https://semver.org/[semantic versioning].


[#_licensing]
== Licensing
Copyright 2018-2023 Cyface GmbH

This file is part of the Cyface Serialization.

The Cyface Serialization is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The Cyface Serialization is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the Cyface Serialization.  If not, see http://www.gnu.org/licenses/.
